name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout the Repo
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Build the Datapusher Docker image
      run: docker build ./ckan-datapusher --tag ${{ secrets.DOCKERHUB_USERNAME }}/ckan-datapusher:$(date +%s)

    - name: Push the Datapusher Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ckan-datapusher:$(date +%s)

    - name: Build the Solr Docker image
      run: docker build ./ckan-solr --tag ${{ secrets.DOCKERHUB_USERNAME }}/ckan-solr:$(date +%s)

    - name: Push the Solr Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ckan-solr:$(date +%s)
      
    - name: Build the CKAN Docker image
      run: docker build ./ckan --tag ${{ secrets.DOCKERHUB_USERNAME }}/ckan:$(date +%s)

    - name: Push the CKAN Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ckan:$(date +%s)