name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout the Repo
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Docker meta - Datapusher
      id: meta-datapusher
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/ckan-datapusher
        tags: |
          type=raw,value={{date 'YYYYMMDD'}}

    - name: Build and push - Datapusher
      uses: docker/build-push-action@v3
      with:
        context: ./ckan-datapusher
        push: true
        tags: ${{ steps.meta.outputs.tags }}

    - name: Docker meta - Solr
      id: meta-solr
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/ckan-solr
        tags: |
          type=raw,value={{date 'YYYYMMDD'}}

    - name: Build and push - Solr
      uses: docker/build-push-action@v3
      with:
        context: ./ckan-solr
        push: true
        tags: ${{ steps.meta.outputs.tags }}

    - name: Docker meta - CKAN
      id: meta-ckan
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/ckan
        tags: |
          type=raw,value={{date 'YYYYMMDD'}}

    - name: Build and push - CKAN
      uses: docker/build-push-action@v3
      with:
        context: ./ckan
        push: true
        tags: ${{ steps.meta.outputs.tags }}
