name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout the Repo
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Build and Push the Datapusher Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./ckan-datapusher
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ckan-datapusher:$(date +%s)
    
    - name: Build and Push the Solr Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./ckan-solr
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ckan-solr:$(date +%s)

    - name: Build and Push the CKAN Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./ckan
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ckan:$(date +%s)